### ISSUE TITLE
No module named 'operators'

### ISSUE THREAD

**Issue by nk7983** [aws-samples/amazon-mwaa-automating-dag-deployment#2]
Received the below error after updating the requirements.txt and deployed the dag to dags folder. May I know how to fix this?

Broken DAG: [/usr/local/airflow/dags/hello-mwaa.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/hello-mwaa.py", line 8, in <module>
    from operators.hello_mwaa_operator import HelloOperator
ModuleNotFoundError: No module named 'operators'

**Comment by umaragu** [comment]
Thank you for raising the issue! Is the error happening during the build process? Can you make sure you have the plugins folder in your local if the error is during the local testing?
